#!/usr/bin/env python3
"""
Prefix-continuation memorisation probe  (JGIM revision, Associate Editor comment 2)

THE QUESTION
------------
The AE's point: "We should assume that reference translation materials are
present in the training data for all models... the issue of memorisation should
be at the forefront. [Sentence shuffling] does not rule out the possibility of
sentence-level or phrase-level memorisation."

Sentence shuffling probes whether a model memorised a document's STRUCTURE.
This probes recall directly: show the model the opening of the real professional
translation and ask it to carry on. If it reproduces the genuine continuation
near-verbatim, it has seen that text before.

THE CONTROL — this is the part that makes it a test rather than an anecdote
--------------------------------------------------------------------------
Formulaic patient-education prose is partly predictable even to a model that has
never seen it, so raw overlap proves nothing on its own. Each item therefore runs
twice, matched on document, language, register and length:

  PROFESSIONAL  prefix from the published professional translation
                -> in training data if anything is
  NOVEL         prefix from another model's forward translation, generated by
                this study in Jan-Feb 2026 and never published anywhere
                -> cannot possibly be in training data

  memorisation signal = overlap(PROFESSIONAL) - overlap(NOVEL)

A signal near zero means the models are predicting, not recalling. A large
positive signal is direct evidence of memorisation of the reference corpus.
Reporting it BY RESOURCE LEVEL also answers the AE's second worry - that
memorisation could be inflating high-resource cells and masking a real gap.

USAGE
-----
    export OPENAI_API_KEY=...  ANTHROPIC_API_KEY=...
    export GOOGLE_API_KEY=...  MOONSHOT_API_KEY=...

    python memorisation_prefix_probe.py --dry-run        # cost estimate, no calls
    python memorisation_prefix_probe.py --sample 6       # ~$15, good pilot
    python memorisation_prefix_probe.py                  # full run, ~$40-70

Keys stay on your machine; nothing is transmitted anywhere but the vendor APIs.
Results are checkpointed after every call, so it is safe to interrupt and resume.
"""
import argparse, json, os, sys, csv, time
from collections import defaultdict
import numpy as np

try:
    import sacrebleu
except ImportError:
    sys.exit("pip install sacrebleu")

PREFIX_WORDS = 100
TARGET_WORDS = 150
HIGH = {'spanish', 'chinese_simplified', 'russian', 'vietnamese'}
LOW = {'tagalog', 'haitian_creole'}

MODELS = {
    'gpt-5.1':         ('openai',    'gpt-5.1'),
    'claude-opus-4.5': ('anthropic', 'claude-opus-4-5-20251101'),
    'gemini-3-pro':    ('google',    'gemini-3-pro-preview'),
    'kimi-k2':         ('moonshot',  'kimi-k2-thinking'),
}

SYSTEM = ("You are reproducing a document you have seen before. Continue the "
          "text exactly as it appears in the original. Do not translate, "
          "summarise, paraphrase, correct or comment. Reproduce the original "
          "wording as closely as you can.")
USER = ("Here is the opening of a document:\n\n{prefix}\n\n"
        "Continue this document from exactly where it stops. "
        "Output only the continuation and nothing else.")


def level(l):
    return 'high' if l in HIGH else ('low' if l in LOW else 'medium')


# ------------------------------------------------------------------ vendors
# These mirror scripts/translation_pipeline.py in the study repo exactly.
# Three differences from a naive implementation, all of which matter:
#   * GPT-5.1 requires max_completion_tokens, not max_tokens
#   * Gemini needs explicit BLOCK_NONE safety settings or it refuses medical text,
#     and the system prompt must be folded into the user prompt
#   * Kimi K2 Thinking needs a 2-hour timeout; the default 10 min is not enough
# Gemini and Kimi are reasoning models: output tokens are consumed by reasoning
# before any text is emitted, so their budgets are set high deliberately.

_moonshot_client = None


def _moonshot():
    global _moonshot_client
    if _moonshot_client is None:
        from openai import OpenAI
        import httpx
        _moonshot_client = OpenAI(
            api_key=os.environ["MOONSHOT_API_KEY"],
            base_url="https://api.moonshot.ai/v1",
            timeout=httpx.Timeout(7200.0, connect=60.0),
        )
    return _moonshot_client


def call(provider, model_id, prefix, max_tokens=600):
    prompt = USER.format(prefix=prefix)

    if provider == 'openai':
        from openai import OpenAI
        r = OpenAI().chat.completions.create(
            model=model_id, temperature=0,
            max_completion_tokens=max_tokens,          # NOT max_tokens for GPT-5.1+
            messages=[{"role": "system", "content": SYSTEM},
                      {"role": "user", "content": prompt}])
        return r.choices[0].message.content or ''

    if provider == 'anthropic':
        import anthropic
        r = anthropic.Anthropic().messages.create(
            model=model_id, max_tokens=max_tokens, temperature=0, system=SYSTEM,
            messages=[{"role": "user", "content": prompt}])
        return ''.join(b.text for b in r.content if getattr(b, 'type', '') == 'text')

    if provider == 'google':
        import google.generativeai as genai
        from google.generativeai.types import HarmCategory, HarmBlockThreshold
        genai.configure(api_key=os.environ['GOOGLE_API_KEY'])
        safety = {
            HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
        }
        model = genai.GenerativeModel(model_id, safety_settings=safety)
        cfg = genai.types.GenerationConfig(
            max_output_tokens=max(max_tokens, 4096), temperature=0)
        r = model.generate_content(f"{SYSTEM}\n\n{prompt}", generation_config=cfg)
        if not r.candidates:
            raise ValueError(f"Gemini returned no candidates: {r}")
        c = r.candidates[0]
        if c.finish_reason == 3:
            raise ValueError("Gemini blocked by safety filter")
        parts = getattr(getattr(c, 'content', None), 'parts', []) or []
        return ''.join(getattr(p, 'text', '') for p in parts)

    if provider == 'moonshot':
        r = _moonshot().chat.completions.create(
            model=model_id, temperature=0, max_tokens=max(max_tokens, 4096),
            messages=[{"role": "system", "content": SYSTEM},
                      {"role": "user", "content": prompt}])
        return r.choices[0].message.content or ''

    raise ValueError(provider)


# ------------------------------------------------------------------ scoring
def overlap(generated, truth):
    """chrF is the right family here: character n-grams work across Chinese,
    Arabic, Korean and Latin scripts alike, where word-level BLEU does not."""
    if not generated.strip() or not truth.strip():
        return None
    return sacrebleu.corpus_chrf([generated], [[truth]]).score


def longest_verbatim(generated, truth, n=8):
    """Longest run of consecutive words reproduced exactly. Verbatim recall of a
    long span is much harder to explain away as prediction than a good chrF."""
    g, t = generated.split(), truth.split()
    if not g or not t:
        return 0
    tset = defaultdict(list)
    for i in range(len(t)):
        tset[t[i]].append(i)
    best = 0
    for i in range(len(g)):
        for j in tset.get(g[i], []):
            k = 0
            while i + k < len(g) and j + k < len(t) and g[i + k] == t[j + k]:
                k += 1
            best = max(best, k)
    return best


# ------------------------------------------------------------------ main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--sample', type=int, default=0, help="use only N documents")
    ap.add_argument('--models', default=','.join(MODELS))
    ap.add_argument('--languages', default='')
    ap.add_argument('--dry-run', action='store_true')
    ap.add_argument('--out', default='output/memorisation_probe')
    a = ap.parse_args()

    src = 'output/medlineplus_results/all_results.json'
    if not os.path.exists(src):
        sys.exit("Run me from the root of the llm-translation-study repo.")
    results = json.load(open(src))
    os.makedirs(a.out, exist_ok=True)
    ckpt = f'{a.out}/checkpoint.jsonl'

    prof, fwd = {}, {}
    for r in results:
        k = (r['doc_id'], r['language'])
        if (r.get('professional_translation') or '').strip():
            prof[k] = r['professional_translation']
        if (r.get('llm_translation') or '').strip():
            fwd.setdefault(k, {})[r['model']] = r['llm_translation']

    docs = sorted({d for d, _ in prof})
    if a.sample:
        docs = docs[::max(1, len(docs) // a.sample)][:a.sample]
    langs = ([x.strip() for x in a.languages.split(',') if x.strip()]
             or sorted({l for _, l in prof}))
    models = [m.strip() for m in a.models.split(',') if m.strip() in MODELS]

    def slice_text(t):
        w = t.split()
        if len(w) < PREFIX_WORDS + 40:
            return None, None
        return ' '.join(w[:PREFIX_WORDS]), ' '.join(w[PREFIX_WORDS:PREFIX_WORDS + TARGET_WORDS])

    jobs = []
    for d in docs:
        for l in langs:
            k = (d, l)
            if k not in prof:
                continue
            p_pre, p_true = slice_text(prof[k])
            if not p_pre:
                continue
            for m in models:
                # control text = a DIFFERENT model's 2026 translation, so the
                # model under test cannot have produced or memorised it
                other = next((mm for mm in fwd.get(k, {}) if mm != m), None)
                if not other:
                    continue
                n_pre, n_true = slice_text(fwd[k][other])
                if not n_pre:
                    continue
                jobs.append(dict(doc_id=d, language=l, model=m, control_from=other,
                                 prof_prefix=p_pre, prof_truth=p_true,
                                 novel_prefix=n_pre, novel_truth=n_true))

    print(f"{len(jobs)} items x 2 conditions = {len(jobs) * 2} API calls")
    print(f"  {len(docs)} documents, {len(langs)} languages, {len(models)} models")
    print(f"  rough cost: ${len(jobs) * 2 * 0.02:.0f}-${len(jobs) * 2 * 0.05:.0f}")
    if a.dry_run:
        return

    done = set()
    if os.path.exists(ckpt):
        for line in open(ckpt):
            try:
                r = json.loads(line)
                if r.get('prof_chrf') is not None and r.get('novel_chrf') is not None:
                    done.add((r['doc_id'], r['language'], r['model']))
            except Exception:
                pass
        print(f"  resuming, {len(done)} already complete")

    fh = open(ckpt, 'a')
    for i, j in enumerate(jobs, 1):
        k = (j['doc_id'], j['language'], j['model'])
        if k in done:
            continue
        prov, mid = MODELS[j['model']]
        row = dict(doc_id=j['doc_id'], language=j['language'],
                   resource_level=level(j['language']), model=j['model'],
                   control_from=j['control_from'])
        for cond, pre, truth in (('prof', j['prof_prefix'], j['prof_truth']),
                                 ('novel', j['novel_prefix'], j['novel_truth'])):
            try:
                gen = call(prov, mid, pre)
                row[f'{cond}_chrf'] = overlap(gen, truth)
                row[f'{cond}_verbatim'] = longest_verbatim(gen, truth)
                row[f'{cond}_chars'] = len(gen)
            except Exception as e:
                row[f'{cond}_error'] = str(e)[:200]
                row[f'{cond}_chrf'] = None
                row[f'{cond}_verbatim'] = None
            time.sleep(0.4)
        if row.get('prof_chrf') is not None and row.get('novel_chrf') is not None:
            row['signal'] = row['prof_chrf'] - row['novel_chrf']
        fh.write(json.dumps(row) + "\n")
        fh.flush()
        if row.get('signal') is None:
            err = row.get('prof_error') or row.get('novel_error') or 'empty output'
            print(f"  [{i}/{len(jobs)}] {j['model']:16} {j['language']:18} FAILED: {err[:110]}")
        else:
            print(f"  [{i}/{len(jobs)}] {j['model']:16} {j['language']:18} "
                  f"prof={row['prof_chrf']:6.1f} novel={row['novel_chrf']:6.1f} "
                  f"signal={row['signal']:+6.1f}")
    fh.close()

    rows = [json.loads(l) for l in open(ckpt)]
    if rows:
        with open(f'{a.out}/memorisation_probe.csv', 'w', newline='') as f:
            cols = sorted({c for r in rows for c in r})
            w = csv.DictWriter(f, fieldnames=cols)
            w.writeheader()
            w.writerows(rows)
    summarise(rows, a.out)


def summarise(rows, out):
    from scipy import stats
    lines = []

    def say(s=''):
        print(s)
        lines.append(s)

    ok = [r for r in rows if r.get('signal') is not None]
    say("=" * 74)
    say("PREFIX-CONTINUATION MEMORISATION PROBE")
    say("=" * 74)
    say(f"n = {len(ok)} matched items\n")
    say("signal = chrF(continuing the professional translation)")
    say("       - chrF(continuing a 2026 translation that cannot be in training data)")
    say("A signal near zero means prediction, not recall.\n")

    p = np.array([r['prof_chrf'] for r in ok])
    n = np.array([r['novel_chrf'] for r in ok])
    t = stats.wilcoxon(p, n)
    say(f"  professional prefix  chrF = {p.mean():6.2f}")
    say(f"  novel prefix         chrF = {n.mean():6.2f}")
    say(f"  SIGNAL                    = {(p - n).mean():+6.2f}   "
        f"Wilcoxon p = {t.pvalue:.3g}")

    say("\n--- by resource level (AE: does memorisation mask a real gap?) ---")
    say(f"{'level':10}{'n':>5}{'prof':>9}{'novel':>9}{'signal':>9}{'verbatim run':>15}")
    by = defaultdict(list)
    for r in ok:
        by[r['resource_level']].append(r)
    for lv in ['high', 'medium', 'low']:
        rs = by.get(lv, [])
        if not rs:
            continue
        say(f"{lv:10}{len(rs):>5}"
            f"{np.mean([x['prof_chrf'] for x in rs]):>9.2f}"
            f"{np.mean([x['novel_chrf'] for x in rs]):>9.2f}"
            f"{np.mean([x['signal'] for x in rs]):>+9.2f}"
            f"{np.mean([x.get('prof_verbatim') or 0 for x in rs]):>15.1f}")
    if len(by.get('high', [])) and len(by.get('low', [])):
        u, pv = stats.mannwhitneyu([x['signal'] for x in by['high']],
                                   [x['signal'] for x in by['low']])
        say(f"\n  high vs low memorisation signal: p = {pv:.3g}")
        say("  (a larger signal for high-resource languages would support the AE's")
        say("   concern that memorisation compresses the resource-level difference)")

    say("\n--- by model ---")
    say(f"{'model':20}{'n':>5}{'prof':>9}{'novel':>9}{'signal':>9}")
    bm = defaultdict(list)
    for r in ok:
        bm[r['model']].append(r)
    for m, rs in sorted(bm.items()):
        say(f"{m:20}{len(rs):>5}"
            f"{np.mean([x['prof_chrf'] for x in rs]):>9.2f}"
            f"{np.mean([x['novel_chrf'] for x in rs]):>9.2f}"
            f"{np.mean([x['signal'] for x in rs]):>+9.2f}")

    say("\n--- longest verbatim reproduced span (consecutive words) ---")
    pv_ = [r.get('prof_verbatim') or 0 for r in ok]
    nv_ = [r.get('novel_verbatim') or 0 for r in ok]
    say(f"  professional prefix: mean {np.mean(pv_):.1f}, max {max(pv_)}")
    say(f"  novel prefix:        mean {np.mean(nv_):.1f}, max {max(nv_)}")
    say("  Long exact runs from the professional prefix only = strongest evidence.")
    say("\n" + "=" * 74)

    with open(f'{out}/memorisation_probe_summary.txt', 'w') as f:
        f.write("\n".join(lines))
    print(f"\nWrote {out}/ — send me memorisation_probe_summary.txt")


if __name__ == '__main__':
    main()
